main: org.comroid.spiroid.Spiroid
name: $name
version: $version
author: $userbase
description: $pluginDescription
api-version: $mcVersionMj

commands:
  spiroid:
    description: Spiroid configuration command
    permission: spiroid.info
    permission-message: "§7[§cSpiroid§7] §cYou are missing the permission: §bspiroid.info§c!"
